"""add rate

Revision ID: 150d5f72418b
Revises: 3af8f1bfd62c
Create Date: 2022-02-09 13:15:23.593550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150d5f72418b'
down_revision = '3af8f1bfd62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_model', sa.Column('rate', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_model', 'rate')
    # ### end Alembic commands ###
